services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WebCamScrapper\Module\CamLandingGenerator\Domain\ReadModel\AffiliateReadModelRepository: '@WebCamScrapper\Module\CamLandingGenerator\Infrastructure\Persistence\Doctrine\DoctrineAffiliateReadModelRepository'

  WebCamScrapper\Module\CamLandingGenerator\Domain\ReadModel\CamUnitReadModelRepository: '@WebCamScrapper\Module\CamLandingGenerator\Infrastructure\Persistence\Doctrine\DoctrineCamUnitReadModelRepository'

  #CreateCamUnit
  WebCamScrapper\Module\CamLandingGenerator\Application\Command\KeepUpdatedCamUnitById\CreateCamUnitHandler:
    tags:
      - {
          name: 'prooph_service_bus.auditor_framework_command_bus.route_target',
          message: WebCamScrapper\Module\CamLandingGenerator\Application\Command\KeepUpdatedCamUnitById\CreateCamUnitCommand
       }

  #CreateAffiliate
  WebCamScrapper\Module\CamLandingGenerator\Application\Command\CreateAffiliate\CreateAffiliateHandler:
    tags:
      - {
          name: 'prooph_service_bus.auditor_framework_command_bus.route_target',
          message: WebCamScrapper\Module\CamLandingGenerator\Application\Command\CreateAffiliate\CreateAffiliateCommand
       }

  #FindJoinPageByAffiliateUrl
  WebCamScrapper\Module\CamLandingGenerator\Application\Query\FindJoinPageByAffiliateUrl\FindJoinPageByAffiliateUrlHandler:
    arguments:
      $cache: "@.app.cache.join_page.taggable"
    tags:
      - {
          name: 'prooph_service_bus.auditor_framework_query_bus.route_target',
          message: WebCamScrapper\Module\CamLandingGenerator\Application\Query\FindJoinPageByAffiliateUrl\FindJoinPageByAffiliateUrlQuery
       }

  WebCamScrapper\Module\CamLandingGenerator\Application\Query\FindJoinPageByAffiliateUrl\JoinPageAssembler:


