<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Command\ForgotPassword\ChangePassword\ChangePasswordHandler' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/oscarlopez1616/auditor-framework/src/Common/Types/Application/CommandBus/CommandHandler.php';
include_once \dirname(__DIR__, 4).'/vendor/oscarlopez1616/auditor-framework/src/Common/Module/SecurityAndAcl/Application/Command/ForgotPassword/ChangePassword/ChangePasswordHandler.php';
include_once \dirname(__DIR__, 4).'/vendor/oscarlopez1616/auditor-framework/src/Common/Types/Application/ApplicationService.php';
include_once \dirname(__DIR__, 4).'/vendor/oscarlopez1616/auditor-framework/src/Common/Types/Application/TransactionAwareApplicationService.php';
include_once \dirname(__DIR__, 4).'/vendor/oscarlopez1616/auditor-framework/src/Common/Module/SecurityAndAcl/Application/Command/ForgotPassword/ChangePassword/ChangePasswordService.php';

return $this->privates['TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Application\\Command\\ForgotPassword\\ChangePassword\\ChangePasswordHandler'] = new \TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Command\ForgotPassword\ChangePassword\ChangePasswordHandler(new \TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Command\ForgotPassword\ChangePassword\ChangePasswordService(($this->privates['TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Infrastructure\\Persistence\\Doctrine\\DoctrineUserReadModelRepository'] ?? $this->load('getDoctrineUserReadModelRepositoryService.php')), ($this->privates['TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Infrastructure\\Persistence\\Doctrine\\DoctrinePasswordRecoveryReadModelRepository'] ?? $this->load('getDoctrinePasswordRecoveryReadModelRepositoryService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->services['TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Types\\Infrastructure\\Persistence\\EventStore\\ProophWriteModelRepository'] ?? $this->load('getProophWriteModelRepositoryService.php'))));
