<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.TheCodeFighters\Bundle\AuditorFramework\Common\Types\Infrastructure\Ui\Cli\CreateNemuruEventStreamIfNotExistsController' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
include_once \dirname(__DIR__, 4).'/vendor/oscarlopez1616/auditor-framework/src/Common/Types/Infrastructure/Ui/Cli/CreateNemuruEventStreamIfNotExistsController.php';

return $this->services['console.command.public_alias.TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Types\\Infrastructure\\Ui\\Cli\\CreateNemuruEventStreamIfNotExistsController'] = new \TheCodeFighters\Bundle\AuditorFramework\Common\Types\Infrastructure\Ui\Cli\CreateNemuruEventStreamIfNotExistsController(($this->services['prooph_event_store.auditor_framework_event_store'] ?? $this->load('getProophEventStore_AuditorFrameworkEventStoreService.php')));
