<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AuditorFramework\Module\CamLandingGenerator\Domain\ReadModel\ProophAffiliateProjection' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/prooph/event-store-symfony-bundle/src/Projection/ReadModelProjection.php';
include_once \dirname(__DIR__, 4).'/src/Module/CamLandingGenerator/Domain/ReadModel/ProophAffiliateProjection.php';

return $this->privates['AuditorFramework\\Module\\CamLandingGenerator\\Domain\\ReadModel\\ProophAffiliateProjection'] = new \AuditorFramework\Module\CamLandingGenerator\Domain\ReadModel\ProophAffiliateProjection();
