<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prooph_service_bus.auditor_framework_event_bus.router' shared service.

include_once \dirname(__DIR__, 4).'/vendor/prooph/service-bus/src/Plugin/Plugin.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/service-bus/src/Plugin/AbstractPlugin.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/service-bus/src/Plugin/Router/MessageBusRouterPlugin.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/service-bus/src/Plugin/Router/EventRouter.php';

return $this->services['prooph_service_bus.auditor_framework_event_bus.router'] = new \Prooph\ServiceBus\Plugin\Router\EventRouter([]);
