<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'prooph_event_store.pdo_mysql_event_store' shared service.

include_once \dirname(__DIR__, 4).'/vendor/prooph/event-store/src/ReadOnlyEventStore.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/event-store/src/EventStore.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/pdo-event-store/src/PdoEventStore.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/pdo-event-store/src/MySqlEventStore.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/common/src/Messaging/MessageFactory.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/common/src/Messaging/FQCNMessageFactory.php';
include_once \dirname(__DIR__, 4).'/vendor/oscarlopez1616/auditor-framework/src/Common/Types/Infrastructure/Persistence/EventStore/MessageFactory.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/pdo-event-store/src/PersistenceStrategy.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/pdo-event-store/src/HasQueryHint.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/pdo-event-store/src/PersistenceStrategy/MySqlSingleStreamStrategy.php';

return $this->privates['prooph_event_store.pdo_mysql_event_store'] = new \Prooph\EventStore\Pdo\MySqlEventStore(new \TheCodeFighters\Bundle\AuditorFramework\Common\Types\Infrastructure\Persistence\EventStore\MessageFactory(), ($this->privates['prooph_event_store.connection.doctrine_pdo_connection'] ?? $this->load('getProophEventStore_Connection_DoctrinePdoConnectionService.php')), new \Prooph\EventStore\Pdo\PersistenceStrategy\MySqlSingleStreamStrategy(), 1000, '_event_streams');
