jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    metadata:
        auto_detection: false
        directories:
            RestResource:
                namespace_prefix: "TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Types\\Infrastructure\\Ui\\Http\\Rest\\Resource"
                path: '%kernel.project_dir%/vendor/oscarlopez1616/auditor-framework/src/Common/Types/Infrastructure/Ui/Http/Rest/ResourceRender/JmsSerializer/Annotation'
