# config/packages/security.yaml
security:
  access_decision_manager:
    strategy: affirmative
    allow_if_all_abstain: false
  providers:
    user_provider:
      id: TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Infrastructure\Symfony\Security\UserProvider

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    api_token:
      pattern: ^/api/token$
      security: false

    api_healthcheck:
      pattern: ^/api/healthcheck/
      security: false

    user_process_patch_forgot_password_change_password:
      request_matcher: TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Infrastructure\Symfony\Security\CustomFirewallRequestMatcher
      security: false

    user_by_email:
      pattern: ^/api/security_and_acl/user/user_name/([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)
      security: false

    user_by_id:
      pattern: ^/api/security_and_acl/user/([a-zA-Z0-9_\-\.]+).(\/)?$
      security: false

    get_join_page:
      pattern: ^/api/cam_landing_creator/join_page/([a-zA-Z0-9_\-\.]+).(\/)?.*$
      security: false

    api:
      pattern: ^/api
      security: true
      stateless: true
      oauth2: true

  encoders:
    TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Domain\User\User:
      algorithm: 'argon2i'
      memory_cost: 1024
      time_cost: 3
      threads: 2
