---
- name: Setting environment ...
  hosts: localhost
  vars:
    ansible_python_interpreter: "/usr/bin/python"

  tasks:

    - name: Create databases
      mysql_db:
        name: "{{item}}"
        state: present
        login_user: "root"
        login_password: "root"
        login_host: "0.0.0.0"
        config_file: false
      with_items:
        - auditor_framework
        - auditor_framework_event_store


