AuditorFramework\Module\CamLandingGenerator\Domain\VO\CamUnitContent:
    exclusion_policy: ALL
    properties:
      wbmerTwitter:
          expose: true
          type: AuditorFramework\Module\CamLandingGenerator\Domain\VO\WbmerTwitter
