<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AuditorFramework\Module\CamLandingGenerator\Application\Command\CreateAffiliate\CreateAffiliateHandler' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/oscarlopez1616/auditor-framework/src/Common/Types/Application/CommandBus/CommandHandler.php';
include_once \dirname(__DIR__, 4).'/src/Module/CamLandingGenerator/Application/Command/CreateAffiliate/CreateAffiliateHandler.php';

return $this->privates['AuditorFramework\\Module\\CamLandingGenerator\\Application\\Command\\CreateAffiliate\\CreateAffiliateHandler'] = new \AuditorFramework\Module\CamLandingGenerator\Application\Command\CreateAffiliate\CreateAffiliateHandler(($this->services['TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Types\\Infrastructure\\Persistence\\EventStore\\ProophWriteModelRepository'] ?? $this->load('getProophWriteModelRepositoryService.php')));
