<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Infrastructure\Persistence\Projection\MysqlPasswordRecoveryReadModel' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/prooph/event-store/src/Projection/ReadModel.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/event-store/src/Projection/AbstractReadModel.php';
include_once \dirname(__DIR__, 4).'/vendor/oscarlopez1616/auditor-framework/src/Common/Module/SecurityAndAcl/Domain/PasswordRecovery/ReadModel/PasswordRecoveryReadModel.php';
include_once \dirname(__DIR__, 4).'/vendor/oscarlopez1616/auditor-framework/src/Common/Module/SecurityAndAcl/Infrastructure/Persistence/Projection/MysqlPasswordRecoveryReadModel.php';

return $this->privates['TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Infrastructure\\Persistence\\Projection\\MysqlPasswordRecoveryReadModel'] = new \TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Infrastructure\Persistence\Projection\MysqlPasswordRecoveryReadModel(($this->services['doctrine.dbal.default_connection'] ?? $this->getDoctrine_Dbal_DefaultConnectionService()));
