<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prooph_service_bus.auditor_framework_query_bus.router' shared service.

include_once \dirname(__DIR__, 4).'/vendor/prooph/service-bus/src/Plugin/Plugin.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/service-bus/src/Plugin/AbstractPlugin.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/service-bus/src/Plugin/Router/MessageBusRouterPlugin.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/service-bus/src/Plugin/Router/SingleHandlerRouter.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/service-bus/src/Plugin/Router/QueryRouter.php';

return $this->services['prooph_service_bus.auditor_framework_query_bus.router'] = new \Prooph\ServiceBus\Plugin\Router\QueryRouter(['TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Application\\Query\\UserByUsername\\GetUserByUsernameQuery' => 'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Application\\Query\\UserByUsername\\GetUserByUsernameHandler', 'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Application\\Query\\UserIdByUsername\\GetUserIdByUsernameQuery' => 'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Application\\Query\\UserIdByUsername\\GetUserIdByUsernameHandler', 'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Application\\Query\\UserByUserId\\GetUserByUserIdQuery' => 'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Application\\Query\\UserByUserId\\GetUserByUserIdHandler', 'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Application\\Query\\ForgotPassword\\GetPasswordRecoveryQuery' => 'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Application\\Query\\ForgotPassword\\GetPasswordRecoveryHandler', 'AuditorFramework\\Module\\CamLandingGenerator\\Application\\Query\\FindJoinPageByAffiliateUrl\\FindJoinPageByAffiliateUrlQuery' => 'AuditorFramework\\Module\\CamLandingGenerator\\Application\\Query\\FindJoinPageByAffiliateUrl\\FindJoinPageByAffiliateUrlHandler']);
