<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'prooph_event_store.metadata_enricher_plugin.auditor_framework_event_store' shared service.

include_once \dirname(__DIR__, 4).'/vendor/prooph/event-store/src/Plugin/Plugin.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/event-store/src/Plugin/AbstractPlugin.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/event-store/src/Metadata/MetadataEnricherPlugin.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/event-store/src/Metadata/MetadataEnricher.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/event-store/src/Metadata/MetadataEnricherAggregate.php';

return $this->privates['prooph_event_store.metadata_enricher_plugin.auditor_framework_event_store'] = new \Prooph\EventStore\Metadata\MetadataEnricherPlugin(new \Prooph\EventStore\Metadata\MetadataEnricherAggregate([]));
