<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prooph_event_store.projection_manager.cam_landing_generator_cam_unit_projection_manager' shared service.

include_once \dirname(__DIR__, 4).'/vendor/prooph/event-store/src/Projection/ProjectionManager.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/event-store-symfony-bundle/src/ProjectionManagerFactory.php';

return $this->services['prooph_event_store.projection_manager.cam_landing_generator_cam_unit_projection_manager'] = ($this->privates['prooph_event_store.projection_factory'] ?? ($this->privates['prooph_event_store.projection_factory'] = new \Prooph\Bundle\EventStore\ProjectionManagerFactory()))->createProjectionManager(($this->privates['prooph_event_store.pdo_mysql_event_store'] ?? $this->load('getProophEventStore_PdoMysqlEventStoreService.php')), ($this->privates['prooph_event_store.connection.doctrine_pdo_connection'] ?? $this->load('getProophEventStore_Connection_DoctrinePdoConnectionService.php')), 'event_streams', '_projections');
