<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'prooph_event_store.projections_locator' shared service.

return $this->privates['prooph_event_store.projections_locator'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cam_landing_generator_affiliate_projection' => ['privates', 'AuditorFramework\\Module\\CamLandingGenerator\\Domain\\ReadModel\\ProophAffiliateProjection', 'getProophAffiliateProjectionService.php', true],
    'cam_landing_generator_affiliate_projection_manager' => ['privates', 'AuditorFramework\\Module\\CamLandingGenerator\\Domain\\ReadModel\\ProophAffiliateProjection', 'getProophAffiliateProjectionService.php', true],
    'cam_landing_generator_cam_unit_projection' => ['privates', 'AuditorFramework\\Module\\CamLandingGenerator\\Domain\\ReadModel\\ProophCamUnitProjection', 'getProophCamUnitProjectionService.php', true],
    'cam_landing_generator_cam_unit_projection_manager' => ['privates', 'AuditorFramework\\Module\\CamLandingGenerator\\Domain\\ReadModel\\ProophCamUnitProjection', 'getProophCamUnitProjectionService.php', true],
    'security_and_acl_password_recovery_projection' => ['privates', 'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Domain\\PasswordRecovery\\ReadModel\\ProophPasswordRecoveryProjection', 'getProophPasswordRecoveryProjectionService.php', true],
    'security_and_acl_password_recovery_projection_manager' => ['privates', 'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Domain\\PasswordRecovery\\ReadModel\\ProophPasswordRecoveryProjection', 'getProophPasswordRecoveryProjectionService.php', true],
    'security_and_acl_user_projection' => ['privates', 'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Domain\\User\\ReadModel\\ProophUserProjection', 'getProophUserProjectionService.php', true],
    'security_and_acl_user_projection_manager' => ['privates', 'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Domain\\User\\ReadModel\\ProophUserProjection', 'getProophUserProjectionService.php', true],
], [
    'cam_landing_generator_affiliate_projection' => '?',
    'cam_landing_generator_affiliate_projection_manager' => '?',
    'cam_landing_generator_cam_unit_projection' => '?',
    'cam_landing_generator_cam_unit_projection_manager' => '?',
    'security_and_acl_password_recovery_projection' => '?',
    'security_and_acl_password_recovery_projection_manager' => '?',
    'security_and_acl_user_projection' => '?',
    'security_and_acl_user_projection_manager' => '?',
]);
