<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'TheCodeFighters\Bundle\AuditorFramework\Common\Types\Application\UploadCsvKeyValue\UploadCsvKeyValueHandler' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/oscarlopez1616/auditor-framework/src/Common/Types/Application/CommandBus/CommandHandler.php';
include_once \dirname(__DIR__, 4).'/vendor/oscarlopez1616/auditor-framework/src/Common/Types/Application/UploadCsvKeyValue/UploadCsvKeyValueHandler.php';
include_once \dirname(__DIR__, 4).'/vendor/oscarlopez1616/auditor-framework/src/Common/Types/Application/ApplicationService.php';
include_once \dirname(__DIR__, 4).'/vendor/oscarlopez1616/auditor-framework/src/Common/Types/Application/UploadCsvKeyValue/UploadCsvKeyValueService.php';
include_once \dirname(__DIR__, 4).'/vendor/oscarlopez1616/auditor-framework/src/Common/Types/Domain/CloudDocumentManagerAdapter.php';
include_once \dirname(__DIR__, 4).'/vendor/oscarlopez1616/auditor-framework/src/Common/Types/Infrastructure/FileSystem/TheLeagueCloudDocumentManager.php';

return $this->privates['TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Types\\Application\\UploadCsvKeyValue\\UploadCsvKeyValueHandler'] = new \TheCodeFighters\Bundle\AuditorFramework\Common\Types\Application\UploadCsvKeyValue\UploadCsvKeyValueHandler(new \TheCodeFighters\Bundle\AuditorFramework\Common\Types\Application\UploadCsvKeyValue\UploadCsvKeyValueService(new \TheCodeFighters\Bundle\AuditorFramework\Common\Types\Infrastructure\FileSystem\TheLeagueCloudDocumentManager(($this->services['default_filesystem'] ?? $this->load('getDefaultFilesystemService.php')))));
