<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator..AVgILO' shared service.

return $this->privates['.service_locator..AVgILO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'Trikoder\\Bundle\\OAuth2Bundle\\Controller\\AuthorizationController::indexAction' => ['privates', '.service_locator.tU8XB4g', 'get_ServiceLocator_TU8XB4gService.php', true],
    'Trikoder\\Bundle\\OAuth2Bundle\\Controller\\TokenController::indexAction' => ['privates', '.service_locator.tU8XB4g', 'get_ServiceLocator_TU8XB4gService.php', true],
    'Trikoder\\Bundle\\OAuth2Bundle\\Controller\\AuthorizationController:indexAction' => ['privates', '.service_locator.tU8XB4g', 'get_ServiceLocator_TU8XB4gService.php', true],
    'Trikoder\\Bundle\\OAuth2Bundle\\Controller\\TokenController:indexAction' => ['privates', '.service_locator.tU8XB4g', 'get_ServiceLocator_TU8XB4gService.php', true],
], [
    'Trikoder\\Bundle\\OAuth2Bundle\\Controller\\AuthorizationController::indexAction' => '?',
    'Trikoder\\Bundle\\OAuth2Bundle\\Controller\\TokenController::indexAction' => '?',
    'Trikoder\\Bundle\\OAuth2Bundle\\Controller\\AuthorizationController:indexAction' => '?',
    'Trikoder\\Bundle\\OAuth2Bundle\\Controller\\TokenController:indexAction' => '?',
]);
