<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.tU8XB4g' shared service.

return $this->privates['.service_locator.tU8XB4g'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'responseFactory' => ['privates', 'nyholm.psr7.psr17_factory', 'getNyholm_Psr7_Psr17FactoryService.php', true],
    'serverRequest' => ['privates', '.errored..service_locator.tU8XB4g.Psr\\Http\\Message\\ServerRequestInterface', NULL, 'Cannot autowire service ".service_locator.tU8XB4g": it references interface "Psr\\Http\\Message\\ServerRequestInterface" but no such service exists. Did you create a class that implements this interface?'],
], [
    'responseFactory' => '?',
    'serverRequest' => 'Psr\\Http\\Message\\ServerRequestInterface',
]);
