<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Trikoder\Bundle\OAuth2Bundle\Controller\AuthorizationController' shared service.

include_once \dirname(__DIR__, 4).'/vendor/trikoder/oauth2-bundle/Controller/AuthorizationController.php';
include_once \dirname(__DIR__, 4).'/vendor/trikoder/oauth2-bundle/Event/AuthorizationRequestResolveEventFactory.php';
include_once \dirname(__DIR__, 4).'/vendor/trikoder/oauth2-bundle/Converter/ScopeConverterInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/trikoder/oauth2-bundle/Converter/ScopeConverter.php';
include_once \dirname(__DIR__, 4).'/vendor/trikoder/oauth2-bundle/Converter/UserConverterInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/trikoder/oauth2-bundle/Converter/UserConverter.php';

return $this->services['Trikoder\\Bundle\\OAuth2Bundle\\Controller\\AuthorizationController'] = new \Trikoder\Bundle\OAuth2Bundle\Controller\AuthorizationController(($this->privates['League\\OAuth2\\Server\\AuthorizationServer'] ?? $this->load('getAuthorizationServerService.php')), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), new \Trikoder\Bundle\OAuth2Bundle\Event\AuthorizationRequestResolveEventFactory(($this->privates['Trikoder\\Bundle\\OAuth2Bundle\\Converter\\ScopeConverter'] ?? ($this->privates['Trikoder\\Bundle\\OAuth2Bundle\\Converter\\ScopeConverter'] = new \Trikoder\Bundle\OAuth2Bundle\Converter\ScopeConverter())), ($this->privates['Trikoder\\Bundle\\OAuth2Bundle\\Manager\\Doctrine\\ClientManager'] ?? $this->load('getClientManagerService.php'))), ($this->privates['Trikoder\\Bundle\\OAuth2Bundle\\Converter\\UserConverter'] ?? ($this->privates['Trikoder\\Bundle\\OAuth2Bundle\\Converter\\UserConverter'] = new \Trikoder\Bundle\OAuth2Bundle\Converter\UserConverter())));
