<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Trikoder\Bundle\OAuth2Bundle\Manager\Doctrine\AccessTokenManager' shared service.

include_once \dirname(__DIR__, 4).'/vendor/trikoder/oauth2-bundle/Manager/AccessTokenManagerInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/trikoder/oauth2-bundle/Manager/Doctrine/AccessTokenManager.php';

return $this->privates['Trikoder\\Bundle\\OAuth2Bundle\\Manager\\Doctrine\\AccessTokenManager'] = new \Trikoder\Bundle\OAuth2Bundle\Manager\Doctrine\AccessTokenManager(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
