<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Infrastructure\Ui\Cli\CreateInitialUsersIfNotExistsController' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
include_once \dirname(__DIR__, 4).'/vendor/oscarlopez1616/auditor-framework/src/Common/Module/SecurityAndAcl/Infrastructure/Ui/Cli/CreateInitialUsersIfNotExistsController.php';

return $this->services['console.command.public_alias.TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Infrastructure\\Ui\\Cli\\CreateInitialUsersIfNotExistsController'] = new \TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Infrastructure\Ui\Cli\CreateInitialUsersIfNotExistsController(($this->privates['TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Types\\Application\\CommandBus'] ?? $this->load('getCommandBusService.php')), [$this->getEnv('SECURITY_AND_ACL_USER_SUPER_ADMIN_USER_NAME') => $this->getEnv('SECURITY_AND_ACL_USER_SUPER_ADMIN_PASSWORD'), $this->getEnv('SECURITY_AND_ACL_USER_FRONTEND_ADMIN_USER_NAME') => $this->getEnv('SECURITY_AND_ACL_USER_FRONTEND_ADMIN_PASSWORD'), $this->getEnv('SECURITY_AND_ACL_USER_API_GATEWAY_USER_NAME') => $this->getEnv('SECURITY_AND_ACL_USER_API_GATEWAY_PASSWORD'), $this->getEnv('SECURITY_AND_ACL_USER_TASK_RUNNER_USER_NAME') => $this->getEnv('SECURITY_AND_ACL_USER_TASK_RUNNER_PASSWORD')], (\dirname(__DIR__, 4).'/vendor/oscarlopez1616/auditor-framework/src/Common/Module/SecurityAndAcl/Infrastructure/Ui/Cli/initial_users.yaml'));
