<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'TheCodeFighters\Bundle\AuditorFramework\Common\Types\Infrastructure\Ui\Http\Rest\Controller\CsvController' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
include_once \dirname(__DIR__, 4).'/vendor/oscarlopez1616/auditor-framework/src/Common/Types/Infrastructure/Ui/Http/Rest/Controller/Controller.php';
include_once \dirname(__DIR__, 4).'/vendor/oscarlopez1616/auditor-framework/src/Common/Types/Infrastructure/Ui/Http/Rest/Controller/CsvController.php';
include_once \dirname(__DIR__, 4).'/vendor/oscarlopez1616/auditor-framework/src/Common/Types/Infrastructure/Ui/Http/Rest/DataTransformer/IdentifiableDtoResourceToRestResourceDataTransformer.php';
include_once \dirname(__DIR__, 4).'/vendor/oscarlopez1616/auditor-framework/src/Common/Types/Infrastructure/Ui/Http/Rest/DataTransformer/NonIdentifiableDtoResourceToRestResourceDataTransformer.php';

$this->services['TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Types\\Infrastructure\\Ui\\Http\\Rest\\Controller\\CsvController'] = $instance = new \TheCodeFighters\Bundle\AuditorFramework\Common\Types\Infrastructure\Ui\Http\Rest\Controller\CsvController(($this->privates['TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Types\\Application\\CommandBus'] ?? $this->load('getCommandBusService.php')), ($this->privates['TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Types\\Application\\QueryBus'] ?? $this->load('getQueryBusService.php')), ($this->privates['TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Types\\Infrastructure\\Ui\\Http\\Rest\\DataTransformer\\IdentifiableDtoResourceToRestResourceDataTransformer'] ?? ($this->privates['TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Types\\Infrastructure\\Ui\\Http\\Rest\\DataTransformer\\IdentifiableDtoResourceToRestResourceDataTransformer'] = new \TheCodeFighters\Bundle\AuditorFramework\Common\Types\Infrastructure\Ui\Http\Rest\DataTransformer\IdentifiableDtoResourceToRestResourceDataTransformer())), ($this->privates['TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Types\\Infrastructure\\Ui\\Http\\Rest\\DataTransformer\\NonIdentifiableDtoResourceToRestResourceDataTransformer'] ?? ($this->privates['TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Types\\Infrastructure\\Ui\\Http\\Rest\\DataTransformer\\NonIdentifiableDtoResourceToRestResourceDataTransformer'] = new \TheCodeFighters\Bundle\AuditorFramework\Common\Types\Infrastructure\Ui\Http\Rest\DataTransformer\NonIdentifiableDtoResourceToRestResourceDataTransformer())), ($this->services['jms_serializer'] ?? $this->load('getJmsSerializerService.php')));

$instance->setContainer($this);

return $instance;
