<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Trikoder\Bundle\OAuth2Bundle\Command\CreateClientCommand' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
include_once \dirname(__DIR__, 4).'/vendor/trikoder/oauth2-bundle/Command/CreateClientCommand.php';

$this->privates['Trikoder\\Bundle\\OAuth2Bundle\\Command\\CreateClientCommand'] = $instance = new \Trikoder\Bundle\OAuth2Bundle\Command\CreateClientCommand(($this->privates['Trikoder\\Bundle\\OAuth2Bundle\\Manager\\Doctrine\\ClientManager'] ?? $this->load('getClientManagerService.php')));

$instance->setName('trikoder:oauth2:create-client');

return $instance;
