<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'TheCodeFighters\Bundle\AuditorFramework\Common\Types\Application\CommandBus' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/oscarlopez1616/auditor-framework/src/Common/Types/Application/CommandBus.php';

return $this->privates['TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Types\\Application\\CommandBus'] = new \TheCodeFighters\Bundle\AuditorFramework\Common\Types\Application\CommandBus(($this->services['prooph_service_bus.auditor_framework_command_bus'] ?? $this->load('getProophServiceBus_AuditorFrameworkCommandBusService.php')));
