<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'default_filesystem' shared service.

include_once \dirname(__DIR__, 4).'/vendor/league/flysystem/src/FilesystemInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/league/flysystem/src/Plugin/PluggableTrait.php';
include_once \dirname(__DIR__, 4).'/vendor/league/flysystem/src/ConfigAwareTrait.php';
include_once \dirname(__DIR__, 4).'/vendor/league/flysystem/src/Filesystem.php';

return $this->services['default_filesystem'] = new \League\Flysystem\Filesystem(($this->privates['oneup_flysystem.awss3v3_adapter_adapter'] ?? $this->load('getOneupFlysystem_Awss3v3AdapterAdapterService.php')), ['disable_asserts' => false]);
