<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'TheCodeFighters\Bundle\AuditorFramework\Common\Types\Infrastructure\Symfony\EventListener\ExceptionListener' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/oscarlopez1616/auditor-framework/src/Common/Types/Infrastructure/Symfony/EventListener/ExceptionListener.php';

return $this->privates['TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Types\\Infrastructure\\Symfony\\EventListener\\ExceptionListener'] = new \TheCodeFighters\Bundle\AuditorFramework\Common\Types\Infrastructure\Symfony\EventListener\ExceptionListener(($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));
