<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AuditorFramework\Module\CamLandingGenerator\Application\Query\FindJoinPageByAffiliateUrl\FindJoinPageByAffiliateUrlHandler' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/oscarlopez1616/auditor-framework/src/Common/Types/Application/QueryBus/QueryHandler.php';
include_once \dirname(__DIR__, 4).'/src/Module/CamLandingGenerator/Application/Query/FindJoinPageByAffiliateUrl/FindJoinPageByAffiliateUrlHandler.php';
include_once \dirname(__DIR__, 4).'/src/Module/CamLandingGenerator/Domain/ReadModel/AffiliateReadModelRepository.php';
include_once \dirname(__DIR__, 4).'/src/Module/CamLandingGenerator/Infrastructure/Persistence/Doctrine/DoctrineAffiliateReadModelRepository.php';
include_once \dirname(__DIR__, 4).'/src/Module/CamLandingGenerator/Domain/ReadModel/CamUnitReadModelRepository.php';
include_once \dirname(__DIR__, 4).'/src/Module/CamLandingGenerator/Infrastructure/Persistence/Doctrine/DoctrineCamUnitReadModelRepository.php';
include_once \dirname(__DIR__, 4).'/src/Module/CamLandingGenerator/Application/Query/FindJoinPageByAffiliateUrl/JoinPageAssembler.php';

$a = ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService());

return $this->privates['AuditorFramework\\Module\\CamLandingGenerator\\Application\\Query\\FindJoinPageByAffiliateUrl\\FindJoinPageByAffiliateUrlHandler'] = new \AuditorFramework\Module\CamLandingGenerator\Application\Query\FindJoinPageByAffiliateUrl\FindJoinPageByAffiliateUrlHandler(new \AuditorFramework\Module\CamLandingGenerator\Infrastructure\Persistence\Doctrine\DoctrineAffiliateReadModelRepository($a), new \AuditorFramework\Module\CamLandingGenerator\Infrastructure\Persistence\Doctrine\DoctrineCamUnitReadModelRepository($a), new \AuditorFramework\Module\CamLandingGenerator\Application\Query\FindJoinPageByAffiliateUrl\JoinPageAssembler(), ($this->services['app.cache.join_page'] ?? $this->getApp_Cache_JoinPageService()));
