<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AuditorFramework\Module\CamLandingGenerator\Infrastructure\Persistence\Projection\MysqlCamUnitProjector' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/prooph/event-store/src/Projection/ReadModel.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/event-store/src/Projection/AbstractReadModel.php';
include_once \dirname(__DIR__, 4).'/src/Module/CamLandingGenerator/Domain/ReadModel/CamUnitProjector.php';
include_once \dirname(__DIR__, 4).'/src/Module/CamLandingGenerator/Infrastructure/Persistence/Projection/MysqlCamUnitProjector.php';

return $this->privates['AuditorFramework\\Module\\CamLandingGenerator\\Infrastructure\\Persistence\\Projection\\MysqlCamUnitProjector'] = new \AuditorFramework\Module\CamLandingGenerator\Infrastructure\Persistence\Projection\MysqlCamUnitProjector(($this->services['doctrine.dbal.default_connection'] ?? $this->getDoctrine_Dbal_DefaultConnectionService()), ($this->services['app.cache.join_page'] ?? $this->getApp_Cache_JoinPageService()));
