<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Infrastructure\TrikoderOauth2\OauthClientService' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/oscarlopez1616/auditor-framework/src/Common/Module/SecurityAndAcl/Infrastructure/TrikoderOauth2/OauthClientService.php';
include_once \dirname(__DIR__, 4).'/vendor/oscarlopez1616/auditor-framework/src/Common/Module/SecurityAndAcl/Infrastructure/TrikoderOauth2/OauthClientRepository.php';
include_once \dirname(__DIR__, 4).'/vendor/oscarlopez1616/auditor-framework/src/Common/Module/SecurityAndAcl/Infrastructure/Persistence/Doctrine/DoctrineOauthClientRepository.php';

return $this->privates['TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Infrastructure\\TrikoderOauth2\\OauthClientService'] = new \TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Infrastructure\TrikoderOauth2\OauthClientService(new \TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Infrastructure\Persistence\Doctrine\DoctrineOauthClientRepository(($this->privates['Trikoder\\Bundle\\OAuth2Bundle\\Manager\\Doctrine\\ClientManager'] ?? $this->load('getClientManagerService.php'))));
