<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oneup_flysystem.awss3v3_adapter_adapter' shared service.

include_once \dirname(__DIR__, 4).'/vendor/league/flysystem/src/ReadInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/league/flysystem/src/AdapterInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/league/flysystem/src/Adapter/AbstractAdapter.php';
include_once \dirname(__DIR__, 4).'/vendor/league/flysystem/src/Adapter/CanOverwriteFiles.php';
include_once \dirname(__DIR__, 4).'/vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php';
include_once \dirname(__DIR__, 4).'/vendor/aws/aws-sdk-php/src/AwsClientInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/aws/aws-sdk-php/src/AwsClientTrait.php';
include_once \dirname(__DIR__, 4).'/vendor/aws/aws-sdk-php/src/AwsClient.php';
include_once \dirname(__DIR__, 4).'/vendor/aws/aws-sdk-php/src/S3/S3ClientInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/aws/aws-sdk-php/src/Api/Parser/PayloadParserTrait.php';
include_once \dirname(__DIR__, 4).'/vendor/aws/aws-sdk-php/src/S3/S3ClientTrait.php';
include_once \dirname(__DIR__, 4).'/vendor/aws/aws-sdk-php/src/S3/S3Client.php';

return $this->privates['oneup_flysystem.awss3v3_adapter_adapter'] = new \League\Flysystem\AwsS3v3\AwsS3Adapter(new \Aws\S3\S3Client(['version' => 'latest', 'region' => $this->getEnv('AWS_REGION'), 'credentials' => ['key' => $this->getEnv('AWS_KEY'), 'secret' => $this->getEnv('AWS_SECRET')]]), $this->getEnv('AWS_S3_BUCKET'), $this->getEnv('AWS_S3_PREFIX'), []);
