<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prooph_service_bus.auditor_framework_command_bus' shared service.

include_once \dirname(__DIR__, 4).'/vendor/prooph/service-bus/src/MessageBus.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/service-bus/src/CommandBus.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/service-bus-symfony-bundle/src/NamedMessageBus.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/service-bus-symfony-bundle/src/NamedMessageBusTrait.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/service-bus-symfony-bundle/src/CommandBus.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/service-bus/src/Plugin/Plugin.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/service-bus/src/Plugin/AbstractPlugin.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/service-bus-symfony-bundle/src/Plugin/DataCollectorPlugin.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/service-bus-symfony-bundle/src/MessageContext/ContextFactory.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/service-bus-symfony-bundle/src/MessageContext/MessageDataConverter.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/service-bus-symfony-bundle/src/MessageContext/DefaultMessageDataConverter.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/service-bus-symfony-bundle/src/Plugin/PsrLoggerPlugin.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/service-bus/src/Plugin/MessageFactoryPlugin.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/common/src/Messaging/MessageFactory.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/common/src/Messaging/FQCNMessageFactory.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/service-bus/src/Plugin/ServiceLocatorPlugin.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/common/src/Messaging/MessageConverter.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/common/src/Messaging/NoOpMessageConverter.php';

$this->services['prooph_service_bus.auditor_framework_command_bus'] = $instance = new \Prooph\Bundle\ServiceBus\CommandBus();

$a = new \Prooph\Bundle\ServiceBus\MessageContext\ContextFactory(new \Prooph\Bundle\ServiceBus\MessageContext\DefaultMessageDataConverter(($this->privates['prooph_service_bus.message_converter'] ?? ($this->privates['prooph_service_bus.message_converter'] = new \Prooph\Common\Messaging\NoOpMessageConverter()))));
$b = new \Symfony\Bridge\Monolog\Logger('command_bus.auditor_framework_command_bus');
$b->pushProcessor(($this->privates['debug.log_processor'] ?? $this->getDebug_LogProcessorService()));
$b->pushHandler(($this->privates['monolog.handler.application'] ?? $this->getMonolog_Handler_ApplicationService()));
$b->pushHandler(($this->privates['monolog.handler.console'] ?? $this->getMonolog_Handler_ConsoleService()));
$b->pushHandler(($this->privates['monolog.handler.main'] ?? $this->getMonolog_Handler_MainService()));
\Symfony\Bundle\FrameworkBundle\DependencyInjection\Compiler\AddDebugLogProcessorPass::configureLogger($b);

$instance->setBusName('auditor_framework_command_bus');
$instance->setBusType('command');
$instance->addPlugin(($this->privates['prooph_service_bus.plugin.stopwatch'] ?? $this->load('getProophServiceBus_Plugin_StopwatchService.php')), 'prooph_service_bus.plugin.stopwatch');
$instance->addPlugin(new \Prooph\Bundle\ServiceBus\Plugin\DataCollectorPlugin($a, ($this->privates['prooph_service_bus.plugin.symfony_data_collector.command_bus'] ?? ($this->privates['prooph_service_bus.plugin.symfony_data_collector.command_bus'] = new \Prooph\Bundle\ServiceBus\Plugin\DataCollector($this, 'command')))), 'prooph_service_bus.auditor_framework_command_bus.plugin.data_collector');
$instance->addPlugin(new \Prooph\Bundle\ServiceBus\Plugin\PsrLoggerPlugin($a, $b), 'prooph_service_bus.auditor_framework_command_bus.plugin.psr_logger');
$instance->addPlugin(new \Prooph\ServiceBus\Plugin\MessageFactoryPlugin(new \Prooph\Common\Messaging\FQCNMessageFactory()), 'prooph_service_bus.message_factory_plugin.auditor_framework_command_bus');
$instance->addPlugin(($this->services['prooph_service_bus.auditor_framework_command_bus.router'] ?? $this->load('getProophServiceBus_AuditorFrameworkCommandBus_RouterService.php')), 'prooph_service_bus.auditor_framework_command_bus.router');
$instance->addPlugin(new \Prooph\ServiceBus\Plugin\ServiceLocatorPlugin(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'AuditorFramework\\Module\\CamLandingGenerator\\Application\\Command\\CreateAffiliate\\CreateAffiliateHandler' => ['privates', 'AuditorFramework\\Module\\CamLandingGenerator\\Application\\Command\\CreateAffiliate\\CreateAffiliateHandler', 'getCreateAffiliateHandlerService.php', true],
    'AuditorFramework\\Module\\CamLandingGenerator\\Application\\Command\\CreateCamUnit\\CreateCamUnitHandler' => ['privates', 'AuditorFramework\\Module\\CamLandingGenerator\\Application\\Command\\CreateCamUnit\\CreateCamUnitHandler', 'getCreateCamUnitHandlerService.php', true],
    'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Application\\Command\\AddRoleToUser\\AddRoleToUserHandler' => ['privates', 'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Application\\Command\\AddRoleToUser\\AddRoleToUserHandler', 'getAddRoleToUserHandlerService.php', true],
    'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Application\\Command\\BlockUser\\BlockUserHandler' => ['privates', 'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Application\\Command\\BlockUser\\BlockUserHandler', 'getBlockUserHandlerService.php', true],
    'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Application\\Command\\ChangePassword\\ChangePasswordHandler' => ['privates', 'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Application\\Command\\ChangePassword\\ChangePasswordHandler', 'getChangePasswordHandlerService.php', true],
    'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Application\\Command\\CreateUser\\CreateUserHandler' => ['privates', 'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Application\\Command\\CreateUser\\CreateUserHandler', 'getCreateUserHandlerService.php', true],
    'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Application\\Command\\ForgotPassword\\ChangePassword\\ChangePasswordHandler' => ['privates', 'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Application\\Command\\ForgotPassword\\ChangePassword\\ChangePasswordHandler', 'getChangePasswordHandler2Service.php', true],
    'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Application\\Command\\ForgotPassword\\CreateAndSendPasswordRecovery\\CreateAndSendPasswordRecoveryHandler' => ['privates', 'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Application\\Command\\ForgotPassword\\CreateAndSendPasswordRecovery\\CreateAndSendPasswordRecoveryHandler', 'getCreateAndSendPasswordRecoveryHandlerService.php', true],
    'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Application\\Command\\UnblockUser\\UnblockUserHandler' => ['privates', 'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Application\\Command\\UnblockUser\\UnblockUserHandler', 'getUnblockUserHandlerService.php', true],
    'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Types\\Application\\UploadCsvKeyValue\\UploadCsvKeyValueHandler' => ['privates', 'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Types\\Application\\UploadCsvKeyValue\\UploadCsvKeyValueHandler', 'getUploadCsvKeyValueHandlerService.php', true],
], [
    'AuditorFramework\\Module\\CamLandingGenerator\\Application\\Command\\CreateAffiliate\\CreateAffiliateHandler' => '?',
    'AuditorFramework\\Module\\CamLandingGenerator\\Application\\Command\\CreateCamUnit\\CreateCamUnitHandler' => '?',
    'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Application\\Command\\AddRoleToUser\\AddRoleToUserHandler' => '?',
    'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Application\\Command\\BlockUser\\BlockUserHandler' => '?',
    'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Application\\Command\\ChangePassword\\ChangePasswordHandler' => '?',
    'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Application\\Command\\CreateUser\\CreateUserHandler' => '?',
    'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Application\\Command\\ForgotPassword\\ChangePassword\\ChangePasswordHandler' => '?',
    'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Application\\Command\\ForgotPassword\\CreateAndSendPasswordRecovery\\CreateAndSendPasswordRecoveryHandler' => '?',
    'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Application\\Command\\UnblockUser\\UnblockUserHandler' => '?',
    'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Types\\Application\\UploadCsvKeyValue\\UploadCsvKeyValueHandler' => '?',
])), 'auditor_framework_command_bus.plugin.service_locator');

return $instance;
