<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'prooph_service_bus.plugin.stopwatch' shared service.

include_once \dirname(__DIR__, 4).'/vendor/prooph/service-bus/src/Plugin/Plugin.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/service-bus/src/Plugin/AbstractPlugin.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/service-bus-symfony-bundle/src/Plugin/StopwatchPlugin.php';

return $this->privates['prooph_service_bus.plugin.stopwatch'] = new \Prooph\Bundle\ServiceBus\Plugin\StopwatchPlugin(($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
