<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'prooph_event_store.connection.doctrine_pdo_connection' shared service.

return $this->privates['prooph_event_store.connection.doctrine_pdo_connection'] = ($this->services['doctrine.dbal.event_store_connection'] ?? $this->load('getDoctrine_Dbal_EventStoreConnectionService.php'))->getWrappedConnection();
