<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Prooph\Bundle\EventStore\Command\ProjectionNamesCommand' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/event-store-symfony-bundle/src/Command/FormatsOutput.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/event-store-symfony-bundle/src/Command/ProjectionNamesCommand.php';

$this->privates['Prooph\\Bundle\\EventStore\\Command\\ProjectionNamesCommand'] = $instance = new \Prooph\Bundle\EventStore\Command\ProjectionNamesCommand(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cam_landing_generator_affiliate_projection_manager' => ['services', 'prooph_event_store.projection_manager.cam_landing_generator_affiliate_projection_manager', 'getProophEventStore_ProjectionManager_CamLandingGeneratorAffiliateProjectionManagerService.php', true],
    'cam_landing_generator_cam_unit_projection_manager' => ['services', 'prooph_event_store.projection_manager.cam_landing_generator_cam_unit_projection_manager', 'getProophEventStore_ProjectionManager_CamLandingGeneratorCamUnitProjectionManagerService.php', true],
    'security_and_acl_password_recovery_projection_manager' => ['services', 'prooph_event_store.projection_manager.security_and_acl_password_recovery_projection_manager', 'getProophEventStore_ProjectionManager_SecurityAndAclPasswordRecoveryProjectionManagerService.php', true],
    'security_and_acl_user_projection_manager' => ['services', 'prooph_event_store.projection_manager.security_and_acl_user_projection_manager', 'getProophEventStore_ProjectionManager_SecurityAndAclUserProjectionManagerService.php', true],
], [
    'cam_landing_generator_affiliate_projection_manager' => '?',
    'cam_landing_generator_cam_unit_projection_manager' => '?',
    'security_and_acl_password_recovery_projection_manager' => '?',
    'security_and_acl_user_projection_manager' => '?',
]), $this->parameters['prooph_event_store.projection_managers']);

$instance->setName('event-store:projection:names');

return $instance;
