<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prooph_event_store.auditor_framework_event_store' shared service.

include_once \dirname(__DIR__, 4).'/vendor/prooph/event-store/src/ReadOnlyEventStore.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/event-store/src/EventStore.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/event-store-symfony-bundle/src/Factory/ActionEventEmitterFactory.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/event-store-symfony-bundle/src/Factory/DefaultActionEventEmitterFactory.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/event-store-symfony-bundle/src/Factory/EventStoreFactory.php';
include_once \dirname(__DIR__, 4).'/vendor/prooph/event-store-symfony-bundle/src/Factory/DefaultEventStoreFactory.php';

return $this->services['prooph_event_store.auditor_framework_event_store'] = (new \Prooph\Bundle\EventStore\Factory\DefaultEventStoreFactory())->createEventStore('auditor_framework_event_store', ($this->privates['prooph_event_store.pdo_mysql_event_store'] ?? $this->load('getProophEventStore_PdoMysqlEventStoreService.php')), new \Prooph\Bundle\EventStore\Factory\DefaultActionEventEmitterFactory(), 'Prooph\\Common\\Event\\ProophActionEventEmitter', true, new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'prooph_event_store.metadata_enricher_plugin.auditor_framework_event_store' => ['privates', 'prooph_event_store.metadata_enricher_plugin.auditor_framework_event_store', 'getProophEventStore_MetadataEnricherPlugin_AuditorFrameworkEventStoreService.php', true],
], [
    'prooph_event_store.metadata_enricher_plugin.auditor_framework_event_store' => '?',
]), [0 => 'prooph_event_store.metadata_enricher_plugin.auditor_framework_event_store']);
