<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'prooph_event_store.projection_manager_for_projections_locator' shared service.

return $this->privates['prooph_event_store.projection_manager_for_projections_locator'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cam_landing_generator_affiliate_projection' => ['services', 'prooph_event_store.projection_manager.cam_landing_generator_affiliate_projection_manager', 'getProophEventStore_ProjectionManager_CamLandingGeneratorAffiliateProjectionManagerService.php', true],
    'cam_landing_generator_affiliate_projection_manager' => ['services', 'prooph_event_store.projection_manager.cam_landing_generator_affiliate_projection_manager', 'getProophEventStore_ProjectionManager_CamLandingGeneratorAffiliateProjectionManagerService.php', true],
    'cam_landing_generator_cam_unit_projection' => ['services', 'prooph_event_store.projection_manager.cam_landing_generator_cam_unit_projection_manager', 'getProophEventStore_ProjectionManager_CamLandingGeneratorCamUnitProjectionManagerService.php', true],
    'cam_landing_generator_cam_unit_projection_manager' => ['services', 'prooph_event_store.projection_manager.cam_landing_generator_cam_unit_projection_manager', 'getProophEventStore_ProjectionManager_CamLandingGeneratorCamUnitProjectionManagerService.php', true],
    'security_and_acl_password_recovery_projection' => ['services', 'prooph_event_store.projection_manager.security_and_acl_password_recovery_projection_manager', 'getProophEventStore_ProjectionManager_SecurityAndAclPasswordRecoveryProjectionManagerService.php', true],
    'security_and_acl_password_recovery_projection_manager' => ['services', 'prooph_event_store.projection_manager.security_and_acl_password_recovery_projection_manager', 'getProophEventStore_ProjectionManager_SecurityAndAclPasswordRecoveryProjectionManagerService.php', true],
    'security_and_acl_user_projection' => ['services', 'prooph_event_store.projection_manager.security_and_acl_user_projection_manager', 'getProophEventStore_ProjectionManager_SecurityAndAclUserProjectionManagerService.php', true],
    'security_and_acl_user_projection_manager' => ['services', 'prooph_event_store.projection_manager.security_and_acl_user_projection_manager', 'getProophEventStore_ProjectionManager_SecurityAndAclUserProjectionManagerService.php', true],
], [
    'cam_landing_generator_affiliate_projection' => '?',
    'cam_landing_generator_affiliate_projection_manager' => '?',
    'cam_landing_generator_cam_unit_projection' => '?',
    'cam_landing_generator_cam_unit_projection_manager' => '?',
    'security_and_acl_password_recovery_projection' => '?',
    'security_and_acl_password_recovery_projection_manager' => '?',
    'security_and_acl_user_projection' => '?',
    'security_and_acl_user_projection_manager' => '?',
]);
