<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXZbKj6b\AppApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXZbKj6b/AppApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXZbKj6b.legacy');

    return;
}

if (!\class_exists(AppApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXZbKj6b\AppApp_KernelDevDebugContainer::class, AppApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXZbKj6b\AppApp_KernelDevDebugContainer([
    'container.build_hash' => 'XZbKj6b',
    'container.build_id' => '584a3a38',
    'container.build_time' => 1577982099,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXZbKj6b');
