<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXWLSgUj\AppApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXWLSgUj/AppApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXWLSgUj.legacy');

    return;
}

if (!\class_exists(AppApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXWLSgUj\AppApp_KernelDevDebugContainer::class, AppApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXWLSgUj\AppApp_KernelDevDebugContainer([
    'container.build_hash' => 'XWLSgUj',
    'container.build_id' => '7a6cf221',
    'container.build_time' => 1577980747,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXWLSgUj');
