<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWuXx0Z7\AppApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWuXx0Z7/AppApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWuXx0Z7.legacy');

    return;
}

if (!\class_exists(AppApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWuXx0Z7\AppApp_KernelDevDebugContainer::class, AppApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWuXx0Z7\AppApp_KernelDevDebugContainer([
    'container.build_hash' => 'WuXx0Z7',
    'container.build_id' => '366a390b',
    'container.build_time' => 1577990112,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWuXx0Z7');
