<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_twig_error_test' => [['code', '_format'], ['_controller' => 'twig.controller.preview_error::previewErrorPageAction', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'oauth2_authorize' => [[], ['_controller' => 'Trikoder\\Bundle\\OAuth2Bundle\\Controller\\AuthorizationController::indexAction'], [], [['text', '/authorize']], [], []],
    'oauth2_token' => [[], ['_controller' => 'Trikoder\\Bundle\\OAuth2Bundle\\Controller\\TokenController::indexAction'], [], [['text', '/token']], [], []],
    'post_cam_unit' => [[], ['_controller' => 'AuditorFramework\\Module\\CamLandingGenerator\\Infrastructure\\Ui\\Http\\Rest\\Controller\\CamUnitController::postCamUnit'], [], [['text', '/api/cam_landing_creator/cam_unit/']], [], []],
    'post_affiliate' => [[], ['_controller' => 'AuditorFramework\\Module\\CamLandingGenerator\\Infrastructure\\Ui\\Http\\Rest\\Controller\\AffiliateController::postAffiliate'], [], [['text', '/api/cam_landing_creator/affiliate/']], [], []],
    'get_join_page' => [['id'], ['_controller' => 'AuditorFramework\\Module\\CamLandingGenerator\\Infrastructure\\Ui\\Http\\Rest\\Controller\\JoinPageController::getJoinPage'], [], [['text', '/'], ['variable', '/', '[^/]++', 'id'], ['text', '/api/cam_landing_creator/join_page']], [], []],
    'get_forgot_password' => [['passwordRecoveryId', 'userName'], ['_controller' => 'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Infrastructure\\Ui\\Http\\Rest\\Controller\\UserController::getPasswordRecoveryAction'], [], [['variable', '/', '[^/]++', 'userName'], ['variable', '/', '[^/]++', 'passwordRecoveryId'], ['text', '/api/security_and_acl/user/password']], [], []],
    'user_id_by_username' => [['username'], ['_controller' => 'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Infrastructure\\Ui\\Http\\Rest\\Controller\\UserController::getUserByUserName'], [], [['text', '/'], ['variable', '/', '[^/]++', 'username'], ['text', '/api/security_and_acl/user/user_name']], [], []],
    'user_by_user_id' => [['userId'], ['_controller' => 'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Infrastructure\\Ui\\Http\\Rest\\Controller\\UserController::getUserByUserId'], [], [['text', '/'], ['variable', '/', '[^/]++', 'userId'], ['text', '/api/security_and_acl/user']], [], []],
    'user_profile' => [[], ['_controller' => 'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Infrastructure\\Ui\\Http\\Rest\\Controller\\UserController::getAclUser'], [], [['text', '/api/security_and_acl/user/acl/profile']], [], []],
    'post_create_user_action' => [[], ['_controller' => 'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Infrastructure\\Ui\\Http\\Rest\\Controller\\UserController::postUserAction'], [], [['text', '/api/security_and_acl/user/']], [], []],
    'patch' => [[], ['_controller' => 'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Module\\SecurityAndAcl\\Infrastructure\\Ui\\Http\\Rest\\Controller\\UserController::patchAction'], [], [['text', '/api/security_and_acl/user/']], [], []],
    'post_csv_key_value' => [[], ['_controller' => 'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Types\\Infrastructure\\Ui\\Http\\Rest\\Controller\\CsvController::postCsvKeyValue'], [], [['text', '/api/common/csv/']], [], []],
    'get_ping' => [[], ['_controller' => 'TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Types\\Infrastructure\\Ui\\Http\\Rest\\Controller\\HealthCheckController::getPing'], [], [['text', '/api/healthcheck/ping']], [], []],
];
